// app/src/app/login/login.component.ts


import { Component, inject } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import axios from 'axios';
import { ReactiveFormsModule } from '@angular/forms';
import { MatInputModule } from '@angular/material/input';
import{ MatFormFieldModule } from '@angular/material/form-field';
import {   MatIconModule } from '@angular/material/icon';
import {  MatButtonModule } from '@angular/material/button';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { environment } from '../../environments/environment';

@Component({
  selector: 'app-login',
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatInputModule,
    MatFormFieldModule,
    MatButtonModule,
    MatIconModule,
    RouterModule,
    MatSnackBarModule
  ],

  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  loginForm: FormGroup;
  hidePassword = true;
  router = inject(Router);
  snackBar = inject(MatSnackBar)

  constructor(private fb: FormBuilder) {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]]
    });
  }

  onSubmit(): void {
    if (this.loginForm.invalid) {
      return;
    }

    const { email, password } = this.loginForm.value;

    axios
      .post(`${environment.api}/login`, { email, password })
      .then(response => {
        const result = response.data;
        if (result.token) {
          localStorage.setItem('authToken', result.token);
          this.snackBar.open('Login successful! Redirecting...', 'close', {
            duration: 2000,

          });
          this.router.navigateByUrl('/dashboard');
        }
      })
      .catch(error => {
        console.error('An error occurred:', error.message);
          this.snackBar.open(`Error in login, ${error.message}` , 'close', {
            duration: 2000,
          })
      });
  }
}


<main class="container mx-auto mt-16">
    
    <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="max-w-lg flex flex-col space-y-6 mx-auto bg-white shadow-lg rounded-lg p-8">
        <div class="text-center mb-10">
          <h2 class="text-3xl font-bold text-gray-800 mb-4">Welcome Back!</h2>
          <p class="text-gray-600">Log in to your account and start your wellness journey.</p>
        </div>
      <div class="mb-6">
        <mat-form-field appearance="outline" class="w-full">
          <mat-label>Email</mat-label>
          <input matInput formControlName="email" placeholder="Enter your email" required />
          <mat-error *ngIf="loginForm.get('email')?.hasError('required')">Email is required.</mat-error>
          <mat-error *ngIf="loginForm.get('email')?.hasError('email')">Please enter a valid email.</mat-error>
        </mat-form-field>
      </div>
  
      <div class="mb-6">
        <mat-form-field appearance="outline" class="w-full">
          <mat-label>Password</mat-label>
          <input
            matInput
            formControlName="password"
            [type]="hidePassword ? 'password' : 'text'"
            placeholder="Enter your password"
            required
          />
          <button mat-icon-button matSuffix (click)="hidePassword = !hidePassword">
            <mat-icon>{{ hidePassword ? 'visibility' : 'visibility_off' }}</mat-icon>
          </button>
          <mat-error *ngIf="loginForm.get('password')?.hasError('required')">Password is required.</mat-error>
          <mat-error *ngIf="loginForm.get('password')?.hasError('minlength')">Password must be at least 6 characters long.</mat-error>
        </mat-form-field>
      </div>
  
      <button
        mat-flat-button
        color="primary"
        class="w-full"
        [disabled]="loginForm.invalid"
        type="submit"
      >
        Log In
      </button>
      <div class="text-center">
        <p class="text-gray-600">
          Don't have an account?
          <a routerLink="/signup" class="text-blue-600 font-medium hover:underline">Sign Up</a>
        </p>
      </div>
    </form>
  
  </main>

// my-app/app/login/page.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable react/no-unescaped-entities */
/* eslint-disable react-hooks/rules-of-hooks */
'use client';
import React, { useState } from 'react'

const page = () => {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    const loginUser = async() => {
         try {
           const response = await fetch(
             "http://127.0.0.1:5000/api/login",
             {
               method: "POST",
               headers: {
                 "Content-Type": "application/json",
               },
               body: JSON.stringify({
                 email,
                 password,
               }),
             }
           );

           const result = await response.json();

           if (response.ok) {
             // Store the JWT token in localStorage
             localStorage.setItem("authToken", result.token);

             console.log("Login successful! Redirecting...");
             window.location.href = "/dashboard"; // Redirect to the user dashboard after successful login
           } else {
             console.log("Login failed: " + result.error); // Show error message
           }
         } catch (error: any) {
           console.log("An error occurred: " + error.message);
         }
        
    }
    
  return (
    <div>
          <main className="container mx-auto mt-16">
        <div className="text-center mb-10">
            <h2 className="text-3xl font-bold text-gray-800 mb-4">Welcome Back!</h2>
            <p className="text-gray-600">Log in to your account and start your wellness journey.</p>
        </div>

        <form id="login-form" className="max-w-lg mx-auto bg-white shadow-lg rounded-lg p-8">
            <div className="mb-6">
                <label htmlFor="email" className="block text-gray-700 font-medium mb-2">
                    Enter your email
                </label>
                      <input type="text" id="email" name="email" value={email} onChange={
                          (e) => setEmail(e.target.value)
                } placeholder="Enter your email"
                    className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                    required/>
            </div>

            <div className="mb-6">
                <label htmlFor="password" className="block text-gray-700 font-medium mb-2">Password</label>
                <input type="password" id="password" name="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Enter your password"
                    className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                    required/>
            </div>

            <button type="button" onClick={loginUser}
                className="w-full bg-blue-600 text-white py-3 rounded-lg font-semibold hover:bg-blue-700 transition duration-300">
                Log In
            </button>
        </form>

        <div className="text-center mt-6">
            <p className="text-gray-600">Don't have an account? 
                <a href="/signup" className="text-blue-600 font-medium hover:underline">Sign Up</a>
            </p>
        </div>
    </main>
    </div>
  )
}

export default page
