// app/src/app/signup/signup.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import {ReactiveFormsModule, FormGroup, FormControl, Validators, FormsModule, ValidatorFn, AbstractControl, ValidationErrors} from '@angular/forms';
import {MatSnackBar, MatSnackBarModule} from '@angular/material/snack-bar'
import axios from 'axios';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import {MatIconModule} from '@angular/material/icon'
import { environment } from '../../environments/environment';


@Component({
  selector: 'app-signup',
  imports: [ReactiveFormsModule, CommonModule, FormsModule, MatSnackBarModule,  MatFormFieldModule,
    MatInputModule,
    MatIconModule,
    MatButtonModule,],
  templateUrl: './signup.component.html',
  styleUrl: './signup.component.css'
})
export class SignupComponent {
  snackBar = inject(MatSnackBar);
  signupForm: FormGroup = new FormGroup({
    username: new FormControl('', [Validators.required, Validators.minLength(3)]),
    email: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', [Validators.required, Validators.minLength(6)]),
    confirmPassword: new FormControl('', [
      Validators.required,
      Validators.minLength(6),
      this.passwordMatchValidator(),
    ]),
  });
  passwordVisible =  signal<boolean>(false);
  confirmPasswordVisible =signal<boolean>(false)

  // Toggle password visibility
  togglePasswordVisibility(type: string) {
    if (type === 'password') {
      this.passwordVisible.update((prev) => !prev);
    } else {
      this.confirmPasswordVisible.update((prev) => !prev);
    }
      
  }
  
   passwordMatchValidator(): ValidatorFn {
    return (control: AbstractControl): ValidationErrors | null => {
      const password = control.parent?.get('password')?.value;
      const confirmPassword = control.value;
      return password && confirmPassword && password !== confirmPassword
        ? { passwordsMismatch: true }
        : null;
    };
  }

  handleSubmit(): void {
    if (this.signupForm.invalid) return ;
    axios.post(`${environment.api}/signup`, {
        headers: {
          "Content-Type": "application/json",
        },
        body: this.signupForm.value,
      }).then((response) =>{
        console.log(response.data);
        this.snackBar.open('Signup Successfull', 'Close', {
          duration: 2000,
          });
          }).catch((error) => {
            console.log(error);
            this.snackBar.open('Signup Failed', 'Close', {
              duration: 2000,
              });
      })

}
    
   
}


<main class="container mx-auto mt-16">
    
    <form id="signup-form" class="w-4/6 flex flex-col  mx-auto space-y-6 bg-white shadow-lg rounded-lg p-8" [formGroup]="signupForm">
        <div class="text-center mb-10">
          <h2 class="text-3xl font-bold text-gray-800 mb-4">Create Your Account</h2>
          <p class="text-gray-600">Start your journey to better health and wellness today.</p>
        </div>
        <!-- Username Field -->
        <mat-form-field appearance="outline" class="w-full">
          <mat-label>Username</mat-label>
          <input matInput type="text" id="username" name="username" placeholder="Enter your username"
            formControlName="username" required />
          <mat-error *ngIf="signupForm.get('username')?.invalid && signupForm.get('username')?.touched">
            <div *ngIf="signupForm.get('username')?.hasError('required')">Username is required.</div>
            <div *ngIf="signupForm.get('username')?.hasError('minlength')">Username must be at least 3 characters long.</div>
          </mat-error>
        </mat-form-field>
  
      <!-- Email Field -->
        <mat-form-field appearance="outline" class="w-full">
          <mat-label>Email</mat-label>
          <input matInput type="email" id="email" name="email" placeholder="Enter your email"
            formControlName="email" required />
          <mat-error *ngIf="signupForm.get('email')?.invalid && signupForm.get('email')?.touched">
            <div *ngIf="signupForm.get('email')?.hasError('required')">Email is required.</div>
            <div *ngIf="signupForm.get('email')?.hasError('email')">Please enter a valid email.</div>
          </mat-error>
        </mat-form-field>
  
      <!-- Password Field -->
        <mat-form-field appearance="outline" class="flex flex-row items-center">
          <mat-label>Password</mat-label>
          <input
            matInput
            [type]="passwordVisible() ? 'text' : 'password'"
            formControlName="password"
            placeholder="Enter your password"
            required
          />
          <button
            mat-icon-button
            type="button"
            (click)="togglePasswordVisibility('password')"
            [attr.aria-label]="passwordVisible() ? 'Hide password' : 'Show password'"
          >
            <mat-icon>{{ passwordVisible() ? 'visibility_off' : 'visibility' }}</mat-icon>
          </button>
          <mat-error *ngIf="signupForm.get('password')?.hasError('required')">Password is required.</mat-error>
          <mat-error *ngIf="signupForm.get('password')?.hasError('minlength')">Password must be at least 6 characters long.</mat-error>
        </mat-form-field>
  
  
      <!-- Confirm Password Field -->
        <mat-form-field appearance="outline" class="flex flex-row items-center">
          <mat-label>Confirm Password</mat-label>
          <input matInput    [type]="confirmPasswordVisible() ? 'text' : 'password'"
          id="confirm-password" name="confirm-password" placeholder="Confirm your password"
            formControlName="confirmPassword" required />
            <button
            mat-icon-button
            type="button"
            (click)="togglePasswordVisibility('confirm')"
            [attr.aria-label]="confirmPasswordVisible() ? 'Hide password' : 'Show password'"
          >
            <mat-icon>{{ confirmPasswordVisible() ? 'visibility_off' : 'visibility' }}</mat-icon>
          </button>
          <mat-error *ngIf="signupForm.get('confirmPassword')?.invalid && signupForm.get('confirmPassword')?.touched">
            <div *ngIf="signupForm.get('confirmPassword')?.hasError('required')">Confirm Password is required.</div>
            <div *ngIf="signupForm.get('confirmPassword')?.hasError('minlength')">Confirm Password must be at least 6 characters long.</div>
            <div *ngIf="signupForm.get('confirmPassword')?.hasError('passwordsMismatch')">Passwords do not match.</div>
          </mat-error>
        </mat-form-field>
  
      <!-- Submit Button -->
      <button mat-flat-button color="primary" type="button" (click)="handleSubmit()" [disabled]="signupForm.invalid"
        class="w-full py-3 rounded-lg font-semibold hover:bg-blue-700 transition duration-300">
        Sign Up
      </button>
      <div class="text-center">
        <p class="text-gray-600">Already have an account?
          <a routerLink="/login" class="text-blue-600 font-medium hover:underline">Log In</a>
        </p>
      </div>
    </form>
  
  </main>

// my-app/app/signup/page.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable react-hooks/rules-of-hooks */
'use client';
import React, { useState } from 'react'

const page = () => {
    const [username, setUsername] = useState("test34");
    const [email, setEmail] = useState('test34@yopmail.com');
    const [password, setPassword] = useState('Access@#$1234');
    const [confirmPassword, setConfirmPassword] = useState('Access@#$1234');
    

    const handleSubmit = async() => {

 // Validate password match
 if (password !== confirmPassword) {
   alert("Passwords do not match!");
   return;
 }

 // Prepare data to send to API
 const userData = {
   username: username,
   email: email,
   password: password,
 };

 try {
   const response = await fetch("http://127.0.0.1:5000/api/signup", {
     method: "POST",
     headers: {
       "Content-Type": "application/json",
     },
     body: JSON.stringify(userData),
   });

   const result = await response.json();

   if (response.ok) {
     alert("Signup successful! Please log in.");
     window.location.href = "/login"; // Redirect to login page
   } else {
     alert("Signup failed: " + result.message); // Show error message
   }
 } catch (error: any) {
   alert("An error occurred: " + error.message);
 }
    }

  return (
    <div>
          <main className="container mx-auto mt-16">
        <div className="text-center mb-10">
            <h2 className="text-3xl font-bold text-gray-800 mb-4">Create Your Account</h2>
            <p className="text-gray-600">Start your journey to better health and wellness today.</p>
        </div>

        <form id="signup-form" className="max-w-lg mx-auto bg-white shadow-lg rounded-lg p-8">
            <div className="mb-6">
                <label htmlFor="username" className="block text-gray-700 font-medium mb-2">Username</label>
                      <input type="text" id="username" name="username" placeholder="Enter your username"
                          value={
                              username
                          }
                          onChange={(e) => setUsername(e.target.value)}
                    className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                    required/>
            </div>

            <div className="mb-6">
                <label htmlFor="email" className="block text-gray-700 font-medium mb-2">Email</label>
                      <input type="email" id="email" name="email" placeholder="Enter your email"
                          value={
                              email
                          }
                          onChange={(e) => setEmail(e.target.value)}
                    className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                    required/>
            </div>

            <div className="mb-6">
                <label htmlFor="password" className="block text-gray-700 font-medium mb-2">Password</label>
                      <input type="password" id="password" name="password" placeholder="Enter your password"
                          value={
                              password
                          }
                          onChange={(e) => setPassword(e.target.value)}
                    className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                    required/>
            </div>

            <div className="mb-6">
                <label htmlFor="confirm-password" className="block text-gray-700 font-medium mb-2">Confirm Password</label>
                <input type="password" id="confirm-password" name="confirm-password"
                          placeholder="Confirm your password"
                          value={
                              confirmPassword
                          }
                          onChange={(e) => setConfirmPassword(e.target.value)}

                    className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                    required/>
            </div>

                  <button type="button"
                      onClick={handleSubmit}
                className="w-full bg-blue-600 text-white py-3 rounded-lg font-semibold hover:bg-blue-700 transition duration-300">
                Sign Up
            </button>
        </form>

        <div className="text-center mt-6">
            <p className="text-gray-600">Already have an account? 
                <a href="/login" className="text-blue-600 font-medium hover:underline">Log In</a>
            </p>
        </div>
    </main>

    </div>
  )
}

export default page
